play.http.secret.key = "CHANGE_ME"

db.janusgraph {
  storage {
    backend = berkeleyje
    directory = /opt/thp/thehive/db
  }
  index.search {
    backend = lucene
    directory = /opt/thp/thehive/index
  }
}

storage {
  provider = localfs
  localfs.location = /opt/thp/thehive/data
}
