#!/usr/bin/env python3
"""
Coverage engine - scorecard generator.

Renders a score record as a markdown report suitable for committing. The
report exists so a coverage claim can be audited: every grade names the rules
that fired, the measured latency, and the procedure that produced it.
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

BADGE = {
    'PREVENTED': 'Prevented',
    'DETECTED': 'Detected',
    'GENERIC': 'Generic only',
    'LOGGED': 'Logged only',
    'BLIND': 'Blind',
    'NOTRUN': 'Not run',
    'RUNFAIL': 'Run failed',
}


def render(rec):
    s = rec.get('summary', {})
    out = []
    A = out.append

    A('# Detection coverage scorecard - %s' % rec['chain_id'])
    A('')
    A('> Generated by the homelab-mdr coverage engine. Every grade below comes')
    A('> from executing the technique against the live stack and reading what')
    A('> the SIEM produced - not from counting rules in a file.')
    A('')
    A('**Target:** `%s` (agent %s) | **Scored:** %s' % (
        rec['target']['host'], rec['target']['agent_id'], s.get('scored_utc', 'n/a')))
    A('')
    A('**Coverage: %s%%** (%s/%s points across %s scored steps)' % (
        s.get('coverage_pct'), s.get('coverage_points'),
        s.get('coverage_max'), s.get('steps_scored')))
    A('')

    by = s.get('by_grade', {})
    A('| Outcome | Count | Meaning |')
    A('| --- | --- | --- |')
    A('| Prevented | %d | Stopped before execution by ASR/Defender - nothing to investigate |' % by.get('PREVENTED', 0))
    A('| Detected | %d | A custom rule fired and maps to the technique |' % by.get('DETECTED', 0))
    A('| Generic only | %d | A built-in rule fired: an alert with no technique mapping or priority |' % by.get('GENERIC', 0))
    A('| Logged only | %d | Telemetry reached the SIEM, nothing alerted |' % by.get('LOGGED', 0))
    A('| Blind | %d | No telemetry, no alert |' % by.get('BLIND', 0))
    A('')

    A('## Results by step')
    A('')
    A('| Step | Technique | Procedure | Outcome | Latency | Rules fired |')
    A('| --- | --- | --- | --- | --- | --- |')
    for st in rec['steps']:
        sc = st.get('score', {})
        label = sc.get('grade_label', 'n/a')
        if st.get('mode') == 'custom' or 'custom_command' in st:
            proc = 'custom command'
        else:
            proc = 'Atomic %s test %s' % (
                st.get('atomic'), ','.join(str(n) for n in (st.get('test_numbers') or [])))
        lat = sc.get('detection_latency_s')
        lat_s = '%.1fs' % lat if lat is not None else '-'
        fired = (sc.get('expected_fired') or []) + (sc.get('other_custom_rules') or [])
        if not fired:
            fired = sc.get('generic_rules') or []
        A('| %s %s | %s | %s | **%s** | %s | %s |' % (
            st['id'], st['name'], ', '.join(st.get('expect_mitre', []) or ['-']),
            proc, BADGE.get(label, label), lat_s,
            ', '.join(fired) if fired else '-'))
    A('')

    gaps = [st for st in rec['steps']
            if st.get('score', {}).get('grade_label') in ('BLIND', 'GENERIC', 'LOGGED')]
    if gaps:
        A('## Gaps')
        A('')
        for st in gaps:
            sc = st['score']
            A('**%s - %s** (%s)' % (st['id'], st['name'], ', '.join(st.get('expect_mitre', []))))
            A('')
            A('- Expected rules: %s' % (', '.join(sc.get('expected_rules', [])) or 'none named'))
            A('- Outcome: %s' % BADGE.get(sc['grade_label'], sc['grade_label']))
            if sc.get('generic_rules'):
                A('- Generic rules that did fire: %s' % ', '.join(sc['generic_rules']))
            A('')

    notrun = [st for st in rec['steps']
              if st.get('score', {}).get('grade_label') in ('NOTRUN', 'RUNFAIL')]
    if notrun:
        A('## Excluded from scoring')
        A('')
        A('A step whose attack never executed cannot be a detection gap. These are')
        A('reported separately so a setup failure is never counted as a blind spot.')
        A('')
        for st in notrun:
            A('- **%s %s** - %s' % (st['id'], st['name'],
                                    st['score'].get('reason', 'execution failed')))
        A('')

    lims = rec.get('limitations') or []
    if lims:
        A('## Measurement limitations')
        A('')
        for l in lims:
            A('- %s' % ' '.join(l.split()))
        A('')

    A('## How grades are assigned')
    A('')
    A('A detection counts as coverage only when a rule fires *specifically* on')
    A('the technique executed. A rule that alerts on every PowerShell process is')
    A('not coverage for T1059.001 - it is noise that trains analysts to ignore')
    A('PowerShell. The scorer therefore requires an ATT&CK technique match, not')
    A('merely an alert inside the window: the runner drives Atomic through')
    A('PowerShell, so the harness itself trips the PowerShell rules on almost')
    A('every step, and counting that would report coverage the lab does not have.')
    A('')
    A('Latency is measured from the end of attack execution to the first matching')
    A('alert, not from the start of the tool invocation - a two-minute subnet scan')
    A('would otherwise appear to have a two-minute detection delay.')
    A('')

    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser(description='Render a coverage scorecard.')
    ap.add_argument('score_file')
    ap.add_argument('--out')
    args = ap.parse_args()

    rec = json.load(open(args.score_file))
    md = render(rec)

    out_path = args.out or os.path.join(
        HERE, 'results', 'scorecard-%s.md' % rec['chain_id'])
    with open(out_path, 'w') as fh:
        fh.write(md)

    print('scorecard: %s' % out_path)
    print('lines    : %d' % len(md.split('\n')))
    return 0


if __name__ == '__main__':
    sys.exit(main())
